name: oisely_client
description: Client library for Oisely - The AI Guardian for your Pet's Life

environment:
  sdk: '^3.8.0'

dependencies:
  serverpod_auth_client: 3.2.3
  serverpod_auth_idp_client: 3.2.3
  serverpod_client: 3.2.3

