services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: oisely
      POSTGRES_PASSWORD: "k64gg8f-5b778SZkj77ZUq1uF3zwzm43"
    volumes:
      - oisely_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "l48zXb6OYrFmG7SKG2F1R8JB2DjirDda"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: oisely_test
      POSTGRES_PASSWORD: "z7utcpPfDlcHAFKaqDnNBpNQN-1VH1AW"
    volumes:
      - oisely_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "6j4VxlB6BVI6EC7Y5eLvg3r7XsHEe7MM"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  oisely_data:
  oisely_test_data:
